/**
 * One picture per text in lessons/, shown softly under the words on the lesson page.
 * All in the same gentle picture-book style, calm and pale at the top, where the words go.
 */
export const STYLE = [
  "Children's picture-book illustration in soft watercolor and colored pencil, like a gentle hand-painted storybook.",
  'Muted, soft pastel colors with low saturation. Never bright, neon or high-contrast.',
  'Wide landscape picture. Keep the top 40% pale and simple (soft sky, mist or plain paper texture); the scene sits in the lower part.',
  'People are Taiwanese (East Asian) children and families. Calm, warm, friendly mood.',
  'Absolutely no text, letters, numbers, Chinese characters, writing on signs, logos, frames, borders or watermarks.',
].join(' ');

export const SCENES: Record<string, string> = {
  '1up-1': 'A child with a school backpack stepping out of the front door in the morning, the sun rising, a small bird on a tree branch greeting the child.',
  '1up-2': 'A cozy family at home: father cooking in the kitchen, mother painting at an easel, a small dog barking happily, a child singing.',
  '1up-3': 'Gentle rain over a small pond; flowers lifting their heads, grass swaying, a green frog jumping out at the edge of the pond, singing.',
  '1up-4': 'Night: a thin crescent moon like a little boat, a child in pajamas at the bedroom window waving good night to the moon. Soft blue night.',
  '1up-5': 'A child brushing teeth in front of a bathroom mirror in the morning, smiling, a toothbrush and a cup, soft morning light.',
  '1up-6': 'In a meadow: a giraffe with a long neck, an elephant with a long trunk, a white rabbit with long ears, a cat with a long tail, and a girl with long hair, standing together.',
  '1down-1': 'Spring: a child watering a flower pot on a balcony; a tiny green sprout with one leaf coming out of the soil.',
  '1down-2': 'A puppy and a duckling splashing and swimming together in a gentle river by a grassy bank.',
  '1down-3': 'Morning at home: a child getting dressed and washing their face by themself, a school bag packed neatly on a chair, mother smiling at the door.',
  '1down-4': 'Dragon Boat Festival in Taiwan: dragon boats racing on a river with drummers, families cheering on the bank, a child eating a zongzi rice dumpling.',
  '1down-5': 'A spring meadow: fresh green grass, red flowers, a bird singing on a branch, a child looking around with bright eyes.',
  '1down-6': "Children's Day in a park: children blowing bubbles, jumping rope and singing, a teacher watching, small wrapped gifts.",
  '2up-1': 'Autumn: red and yellow leaves drifting down like letters; a squirrel holding a red leaf, gathering pine cones.',
  '2up-2': 'Mid-Autumn night in a park: a big full moon, a Taiwanese family barbecuing, grandmother telling a story, a child wearing a pomelo peel hat, pomelos on a picnic mat.',
  '2up-3': 'Keelung harbor: a large container ship and a white passenger ship leaving port, a child and father waving from the pier.',
  '2up-4': 'A school playground: a child helping a friend who fell and scraped a knee, walking together toward the school nurse.',
  '2up-5': 'A grandfather and grandchild hiking up a mountain path hand in hand, small houses far below, a cool autumn breeze.',
  '2up-6': 'A school library with tall bookshelves; a child and a younger sister reading a book about the ocean, fish seeming to swim out of the pages.',
  '2down-1': 'Sun Moon Lake in Taiwan: a calm lake among green mountains, a tour boat on the water, bicycles on the lakeside path, soft morning mist.',
  '2down-2': 'The small red Alishan forest train climbing through tall cypress forest, a sea of clouds and the sunrise over the mountains.',
  '2down-3': 'A child giving a hand-drawn card with a carnation to mother, who hugs the child with teary eyes, in a cozy living room.',
  '2down-4': 'Clouds in the sky shaped like sheep, a whale and a sunset-colored dress; a child lying on the grass watching them.',
  '2down-5': 'Summer: a bowl of Taiwanese shaved ice topped with mango and condensed milk, a child and mother eating it happily, hot sun outside.',
  '2down-6': 'A calico cat asleep in a sunny spot on a desk, lying on a child\'s notebook, the child doing homework beside it.',
  '3up-1': 'A child riding a city bus alone for the first time, looking out of the window and pressing the stop bell; grandmother waiting at the bus stop.',
  '3up-2': 'A line of ants carrying eggs and a cookie crumb across the ground near a big tree, dark rain clouds gathering far away.',
  '3up-3': 'An old street in Tainan with traditional houses and a temple; bowls of beef soup, rice pudding and tofu pudding on a small table; father and child eating.',
  '3up-4': 'A grandfather in a bamboo hat watering a vegetable garden with cabbages and green onions; a child crouching to pick bugs off the leaves.',
  '3up-5': "Students giving a big handmade Teacher's Day card to their smiling teacher in a classroom. The card has only drawings of flowers and a sun on it, no words at all.",
  '3up-6': 'A child with a notebook interviewing a friendly school security guard at the school gate in the morning; small children arriving under umbrellas.',
  '3down-1': 'Kenting in southern Taiwan: clear turquoise sea, a child snorkeling among tropical fish and coral, a beach at sunset.',
  '3down-2': 'A box of round golden sun cakes, flaky Taiwanese pastries, on a table; a curious little brother peeking inside, an uncle smiling.',
  '3down-3': 'A family indoors on a typhoon night by candlelight, father making hand shadows of a dog and an eagle on the wall, rain on the window.',
  '3down-4': 'Silkworms eating mulberry leaves in a paper box on a classroom desk, white cocoons and a white silk moth, a child watching closely.',
  '3down-5': 'Lantern Festival night: rabbit and goldfish lanterns over a temple square, paper riddle slips hanging below them, a family eating sweet rice balls, a full moon.',
  '3down-6': 'A child riding a bicycle on a park path for the first time, father far behind waving, wind in the hair.',
  '4up-1': 'Taroko Gorge: towering marble cliffs, a blue-green river far below, swallows flying, a small group in helmets on a trail.',
  '4up-2': 'A spring night in a forest: many fireflies glowing green among the grass and trees, a family watching quietly with a flashlight covered in red.',
  '4up-3': 'A school tug-of-war: a class leaning back together, pulling the rope, a red ribbon on it, classmates cheering.',
  '4up-4': 'A child at a desk by a window writing a letter, a tin box full of collected stones, a closed book with a plain cover (only a small leaf drawn on it, no title), a dreamy starry sky outside.',
  '4up-5': 'A family around a table on a cool winter evening in Taiwan (no snow outside) rolling pink and white rice balls, one shaped like a little snowman, a steaming pot of ginger soup.',
  '4up-6': 'Two classmates in a classroom: one handing a new eraser to the other with a shy, sorry face, the other smiling kindly.',
  '4down-1': 'Hot air balloons of many soft colors rising over green rice fields in Taitung at dawn, mountains behind.',
  '4down-2': 'An old man planting a small tree on a hillside behind a school at dawn; around him a green forest has grown, children playing under the trees.',
  '4down-3': 'The water cycle as a gentle landscape: the sea, rising mist, clouds, rain over mountains, a river flowing past rice fields back to the sea.',
  '4down-4': 'A ferry crossing Kaohsiung harbor toward Cijin island, a family on deck, a big cargo ship, a white lighthouse on a hill.',
  '4down-5': 'The Twin Hearts Stone Weir in Penghu seen from a clifftop: two heart-shaped stone walls in a shallow turquoise sea.',
  '4down-6': 'Two snails on a wooden board in a garden after rain, leaving shiny trails, two children cheering them on.',
  '5up-1': 'Jiufen, a mountain town: a narrow old street of stairs, red lanterns lit at dusk, teahouses on the hillside looking out to the sea.',
  '5up-2': 'Black-faced spoonbills with spoon-shaped bills wading in shallow wetland fish ponds in Tainan, soft winter light.',
  '5up-3': 'A kitchen dusted with flour: a flat, slightly burnt cake next to a tall, fluffy second cake; mother and child laughing together.',
  '5up-4': 'A family sitting around candles in the living room during a power cut, playing cards and laughing, their phones put aside.',
  '5up-5': "A pottery class in Yingge: a child shaping clay on a spinning potter's wheel, shelves of cups and vases, a kiln.",
  '5up-6': 'A grandfather listening to an old wooden radio at a table, eyes closed, humming, a child sitting beside him, warm lamp light.',
  '5down-1': 'Turtle Island off the coast of Yilan at sunrise, dolphins leaping near a small tour boat, milky blue water near the island.',
  '5down-2': 'A school vegetable garden: children watering, weeding and harvesting leafy greens, a compost pile, a teacher helping.',
  '5down-3': 'Honeybees visiting longan flowers in an orchard and a pot of purple lavender on a balcony; a grandfather and child watching.',
  '5down-4': "A father's big, rough hands mending a child's school bag at night by the bedside, soft lamp light.",
  '5down-5': 'A bamboo raft gliding through a green tunnel of mangrove trees in Tainan, fiddler crabs waving big claws on the mud, mudskippers.',
  '5down-6': 'Two girls hugging after making up, a handmade photo book gift open between them.',
  '6up-1': 'New Year\'s Eve in Taipei: fireworks pouring down a tall bamboo-shaped skyscraper, crowds watching, a family making a wish.',
  '6up-2': 'Children cleaning a beach, picking up plastic bottles and bags; a sea turtle swimming in clear water nearby.',
  '6up-3': 'An older student reading a dinosaur picture book with a small first grader in a classroom, the little one pointing excitedly at a long-necked dinosaur.',
  '6up-4': 'A girl with a hearing aid teaching classmates sign language in a classroom, everyone smiling and making hand signs.',
  '6up-5': 'A child and grandmother looking through an old photo album together in afternoon light, a notebook for writing beside them, a closed laptop to one side.',
  '6up-6': 'An old blacksmith shop on an old street: an elderly blacksmith hammering glowing iron over a charcoal forge, sparks flying, a child watching.',
  '6down-1': 'White tung blossoms falling like snow over a mountain path in Miaoli, a grandmother and grandchild walking hand in hand, petals floating on a stream.',
  '6down-2': 'Hsinchu in the autumn wind: rows of orange persimmons drying in the sun on racks, a child in a jacket with windblown hair.',
  '6down-3': 'A sixth-grade classroom in the last week: photos pinned by the blackboard, children folding letters, one friend patting another on the shoulder.',
  '6down-4': 'A child at home with a hand-drawn map of the island of Taiwan with a route drawn around it, photos of mountains, lakes and the sea pinned beside it.',
  '6down-5': 'A child playing Chinese chess with an elderly grandmother in the lounge of a care home, both laughing.',
  '6down-6': 'A father and child lying on the grass by a tent on a mountain at night, a sky full of stars and the Milky Way.',
};

export const promptFor = (id: string) => `${STYLE} Scene: ${SCENES[id]}`;
