import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { synth, tidy, toMp3, transcribe, writeFile } from './lib.mjs';

const PROJECT = fileURLToPath(new URL('../..', import.meta.url));
const OUT_DIR = path.join(PROJECT, 'public/audio/english');
const REPORT = new URL('./report.json', import.meta.url);

const inventory = JSON.parse(fs.readFileSync(new URL('./inventory.json', import.meta.url), 'utf8'));
const report = fs.existsSync(REPORT) ? JSON.parse(fs.readFileSync(REPORT, 'utf8')) : {};

const NUMBERS = ['zero', 'one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten', 'eleven', 'twelve'];
const norm = text => text.toLowerCase()
  .replace(/\b(\d{1,2})\b/g, (m, n) => NUMBERS[Number(n)] ?? m)
  .replace(/-/g, ' ')
  .replace(/[^a-z' ]+/g, ' ')
  .replace(/\s+/g, ' ')
  .trim();

const padded = samples => {
  const out = new Float32Array(samples.length + 24000);
  out.set(samples, 12000);
  return out;
};

const ATTEMPTS = [
  ['af_heart', 0.9], ['af_heart', 0.95], ['af_heart', 1.0], ['af_heart', 0.85],
  ['af_bella', 0.9], ['af_bella', 1.0],
];

const t0 = Date.now();
let done = 0;
for (const clip of inventory) {
  done++;
  if (report[clip.key]?.status === 'pass' || report[clip.key]?.status === 'unverified') continue;
  const input = clip.phonemes ? { phonemes: clip.phonemes } : { text: clip.text };
  const tries = [];
  let chosen = null;

  if (clip.kind === 'sound') {
    const samples = tidy(await synth(input, { voice: 'af_heart', speed: 0.9 }));
    const heard = await transcribe(padded(samples));
    chosen = { samples, voice: 'af_heart', speed: 0.9, heard, status: 'unverified' };
  } else {
    const expect = clip.expect.map(norm);
    for (const [voice, speed] of ATTEMPTS) {
      const samples = tidy(await synth(input, { voice, speed }));
      const heard = await transcribe(padded(samples));
      tries.push({ voice, speed, heard });
      if (expect.includes(norm(heard))) {
        chosen = { samples, voice, speed, heard, status: 'pass' };
        break;
      }
      chosen ??= { samples, voice, speed, heard, status: 'fail' }; // Keep the first attempt if none pass
    }
  }

  writeFile(path.join(OUT_DIR, `${clip.file}.mp3`), toMp3(chosen.samples));
  report[clip.key] = {
    file: clip.file, kind: clip.kind, status: chosen.status, voice: chosen.voice, speed: chosen.speed,
    heard: chosen.heard, seconds: +(chosen.samples.length / 24000).toFixed(2), tries: chosen.status === 'pass' ? tries.length : tries,
  };
  fs.writeFileSync(REPORT, JSON.stringify(report, null, 1));
  console.log(`[${done}/${inventory.length}] ${chosen.status.padEnd(10)} ${clip.key.padEnd(28)} heard ${JSON.stringify(chosen.heard)} (${chosen.voice} ${chosen.speed})`);
}

// Lookup table for the app: key → file name (aliases only where the key is free)
const entries = inventory.map(c => [c.key, c.file]);
const keys = new Set(entries.map(([k]) => k));
inventory.forEach(c => (c.aliases || []).forEach(a => { if (!keys.has(a)) { entries.push([a, c.file]); keys.add(a); } }));
entries.sort(([a], [b]) => a.localeCompare(b));
const manifest = `// Generated by the English audio script (Kokoro-82M, Apache-2.0): what the app says → file in /audio/english/.
// Text not listed here falls back to the device's speech synthesis.
export const ENGLISH_CLIPS: Record<string, string> = {
${entries.map(([k, f]) => `  ${JSON.stringify(k)}: ${JSON.stringify(f)},`).join('\n')}
};
`;
fs.writeFileSync(path.join(PROJECT, 'english/audioClips.ts'), manifest);

const statuses = Object.values(report).reduce((acc, r) => ({ ...acc, [r.status]: (acc[r.status] || 0) + 1 }), {});
console.log('DONE', statuses, 'minutes', ((Date.now() - t0) / 60000).toFixed(1));
