/**
 * Builds zhuyin/fontPolyphones.ts from the bpmfvs reading table (phonic_table_Z.txt).
 * The order of readings is the IVS order used by all bpmfvs zhuyin fonts (e.g. Bpmf Zihi Kai Std):
 * the first reading is the default glyph, the n-th alternative is selected with U+E01E0 + n.
 * Source: https://github.com/ButTaiwan/bpmfvs/blob/master/phonetic/phonic_table_Z.txt (Apache 2.0, © But Ko)
 *   npx tsx scripts/build-font-polyphones.ts <path to phonic_table_Z.txt>
 */
import { readFile, writeFile } from 'fs/promises';
import path from 'path';

const OUT_FILE = path.resolve(import.meta.dirname, '..', 'zhuyin', 'fontPolyphones.ts');

const main = async () => {
  const source = process.argv[2];
  if (!source) throw new Error('Usage: npx tsx scripts/build-font-polyphones.ts <phonic_table_Z.txt>');
  const entries = (await readFile(source, 'utf8'))
    .split(/\r?\n/)
    .map(line => line.split('\t'))
    .filter(parts => parts.length > 4) // char, code, source, 2+ readings
    .map(parts => `${parts[0]}${parts.slice(3).join(',')}`);

  await writeFile(OUT_FILE, `// Generated by scripts/build-font-polyphones.ts — do not edit by hand.
// 破音字讀音順序：bpmfvs 注音IVS字型規格 phonic_table_Z（Apache License 2.0, Copyright 2020 But Ko, https://github.com/ButTaiwan/bpmfvs）
// Format: "<char><reading>,<reading>,…" joined by "|". Only characters with more than one reading are listed.
export const FONT_POLYPHONES_RAW = ${JSON.stringify(entries.join('|'))};
`, 'utf8');
  console.log(`Wrote ${entries.length} polyphonic characters`);
};

main().catch(e => {
  console.error(e);
  process.exit(1);
});
