/**
 * Builds zhuyin/moedictData.ts and downloads 教育部 word recordings for the built-in content.
 * Run with: npx tsx scripts/build-zhuyin-data.ts
 *
 * Data: 萌典 moedict.tw — 教育部《重編國語辭典修訂本》《國語辭典簡編本》, CC BY-ND 3.0 TW.
 */
import { mkdir, writeFile, access, readdir, unlink } from 'fs/promises';
import path from 'path';
import { INITIAL_LESSONS } from '../constants';
import { ZHUYIN_SYMBOLS, TONES } from '../zhuyin/symbols';
import { Heteronym, MOEDICT_API, MOEDICT_AUDIO, parseMoedictEntry, resolveReading, Reading } from '../zhuyin/reading';

const ROOT = path.resolve(import.meta.dirname, '..');
const AUDIO_DIR = path.join(ROOT, 'public', 'audio', 'moedict');
const DATA_FILE = path.join(ROOT, 'zhuyin', 'moedictData.ts');

const sleep = (ms: number) => new Promise(r => setTimeout(r, ms));
const entries = new Map<string, Heteronym[] | null>();

const source = async (word: string): Promise<Heteronym[] | null> => {
  if (entries.has(word)) return entries.get(word)!;
  for (let attempt = 1; attempt <= 3; attempt++) {
    try {
      await sleep(250); // Be gentle with the free service
      const res = await fetch(MOEDICT_API(word), { headers: { 'User-Agent': 'zhuyin-word-match-adventure (family learning game)' } });
      if (res.status === 404) {
        entries.set(word, null);
        return null;
      }
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      const parsed = parseMoedictEntry(await res.json());
      entries.set(word, parsed.length ? parsed : null);
      return entries.get(word)!;
    } catch (e) {
      if (attempt === 3) throw new Error(`Failed to fetch ${word}: ${e}`);
      await sleep(1000 * attempt);
    }
  }
  return null;
};

const exists = (file: string) => access(file).then(() => true, () => false);

const main = async () => {
  const report: Reading[] = [];

  for (const lesson of INITIAL_LESSONS) {
    for (const word of new Set(lesson.vocabulary)) {
      const reading = await resolveReading(word, source, { context: lesson.vocabulary });
      report.push(reading);
      // Single characters as read inside the word, for the spelling and tone games (樂 in 快樂 → ㄌㄜˋ)
      const chars = [...word].filter(ch => /\p{Script=Han}/u.test(ch));
      const syllables = reading.zhuyin.split(' ').filter(Boolean);
      if (chars.length === syllables.length && chars.length > 1) {
        for (let i = 0; i < chars.length; i++) {
          if (!syllables[i].startsWith('˙')) report.push(await resolveReading(chars[i], source, { override: syllables[i] }));
        }
      }
    }
  }
  for (const item of ZHUYIN_SYMBOLS) report.push(await resolveReading(item.example, source));
  for (const tone of TONES) report.push(await resolveReading(tone.example, source, { override: tone.exampleZhuyin }));

  // Download recordings for the readings the game will actually use
  await mkdir(AUDIO_DIR, { recursive: true });
  const wantedIds = [...new Set(report.map(r => r.audioId).filter((id): id is string => !!id))].sort();
  const audioIds: string[] = [];
  let downloaded = 0;
  let totalBytes = 0;
  for (const id of wantedIds) {
    const file = path.join(AUDIO_DIR, `${id}.ogg`);
    if (!(await exists(file))) {
      await sleep(250);
      const res = await fetch(MOEDICT_AUDIO(id, 'ogg'));
      if (!res.ok) {
        console.warn(`Audio ${id} failed: HTTP ${res.status}`);
        continue;
      }
      const bytes = Buffer.from(await res.arrayBuffer());
      await writeFile(file, bytes);
      downloaded++;
      totalBytes += bytes.length;
    }
    audioIds.push(id);
  }

  // Remove recordings no longer used by the built-in content
  for (const file of await readdir(AUDIO_DIR)) {
    if (file.endsWith('.ogg') && !audioIds.includes(file.replace('.ogg', ''))) await unlink(path.join(AUDIO_DIR, file));
  }

  const sortedEntries = Object.fromEntries([...entries.entries()].sort(([a], [b]) => a.localeCompare(b, 'zh-Hant')));
  const header = `// Generated by scripts/build-zhuyin-data.ts — do not edit by hand.
// 資料來源：萌典 moedict.tw（教育部《重編國語辭典修訂本》《國語辭典簡編本》，CC BY-ND 3.0 TW）
import { Heteronym } from './reading';

`;
  const body = `export const BUNDLED_ENTRIES: Record<string, Heteronym[] | null> = ${JSON.stringify(sortedEntries, null, 1)};

// Recordings saved under public/audio/moedict/{id}.ogg
export const BUNDLED_AUDIO_IDS: string[] = ${JSON.stringify(audioIds)};
`;
  await writeFile(DATA_FILE, header + body, 'utf8');

  console.log('\nWord\tZhuyin\tSource\tAudio\tOther readings');
  for (const r of report) {
    const others = r.candidates.filter(c => c !== r.zhuyin).join(' / ');
    console.log(`${r.word}\t${r.zhuyin || '(none)'}\t${r.source}\t${r.audioId || '-'}\t${others}`);
  }
  console.log(`\nEntries: ${entries.size}, audio ids: ${audioIds.length}, newly downloaded: ${downloaded} (${(totalBytes / 1024).toFixed(0)} KB)`);
};

main().catch(e => {
  console.error(e);
  process.exit(1);
});
