/**
 * Converts the stroke files of 教育部《國語注音符號手冊》開放部件 (CC BY 4.0) into zhuyin/strokeData.ts.
 * Download bopomofo_materials_20170213.zip from the handbook site, unzip it, then run:
 *   npx tsx scripts/build-zhuyin-strokes.ts <path to the unzipped xml+svg folder>
 */
import { readdir, readFile, writeFile } from 'fs/promises';
import path from 'path';

const ROOT = path.resolve(import.meta.dirname, '..');
const OUT_FILE = path.join(ROOT, 'zhuyin', 'strokeData.ts');

const findJsonFiles = async (dir: string): Promise<string[]> => {
  const result: string[] = [];
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) result.push(...await findJsonFiles(full));
    else if (entry.name.endsWith('.json')) result.push(full);
  }
  return result;
};

const r = (n: number) => Math.round(n);

const outlineToPath = (outline: any[]) => outline.map(cmd => {
  switch (cmd.type) {
    case 'M': return `M${r(cmd.x)} ${r(cmd.y)}`;
    case 'L': return `L${r(cmd.x)} ${r(cmd.y)}`;
    case 'Q': return `Q${r(cmd.begin.x)} ${r(cmd.begin.y)} ${r(cmd.end.x)} ${r(cmd.end.y)}`;
    case 'C': return `C${r(cmd.begin.x)} ${r(cmd.begin.y)} ${r(cmd.mid.x)} ${r(cmd.mid.y)} ${r(cmd.end.x)} ${r(cmd.end.y)}`;
    default: throw new Error(`Unknown outline command ${cmd.type}`);
  }
}).join('') + 'Z';

const main = async () => {
  const source = process.argv[2];
  if (!source) throw new Error('Usage: npx tsx scripts/build-zhuyin-strokes.ts <xml+svg folder>');

  const data: Record<string, { outline: string; track: number[][] }[]> = {};
  for (const file of await findJsonFiles(source)) {
    const char = String.fromCodePoint(parseInt(path.basename(file, '.json'), 16));
    const strokes = JSON.parse(await readFile(file, 'utf8'));
    data[char] = strokes.map((stroke: any) => ({
      outline: outlineToPath(stroke.outline),
      track: stroke.track.map((p: any) => [r(p.x), r(p.y)]),
    }));
  }

  const chars = Object.keys(data).sort((a, b) => a.codePointAt(0)! - b.codePointAt(0)!);
  const body = chars.map(c => `  '${c}': ${JSON.stringify(data[c])},`).join('\n');
  await writeFile(OUT_FILE, `// Generated by scripts/build-zhuyin-strokes.ts — do not edit by hand.
// 筆順資料：2017 © 教育部，國語注音符號手冊-開放部件（CC BY 4.0 https://creativecommons.org/licenses/by/4.0/deed.zh_TW）
// Coordinates are in a 2150 × 2150 box. \`outline\` is the stroke shape, \`track\` its writing path in order.

export interface ZhuyinStroke {
  outline: string;
  track: number[][];
}

export const ZHUYIN_STROKE_BOX = 2150;

export const ZHUYIN_STROKES: Record<string, ZhuyinStroke[]> = {
${body}
};
`, 'utf8');
  console.log(`Wrote ${chars.length} symbols: ${chars.join('')}`);
};

main().catch(e => {
  console.error(e);
  process.exit(1);
});
